# Generated by Django 4.2.9 on 2024-02-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_studentdepartment_kfupmdepartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kfupmdepartment',
            old_name='name',
            new_name='long_name',
        ),
        migrations.AddField(
            model_name='kfupmdepartment',
            name='short_name',
            field=models.CharField(default='SWE', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
