# Generated by Django 4.2.9 on 2024-02-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_name_kfupmdepartment_long_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpatient',
            name='entry_date',
        ),
    ]
