# Generated by Django 4.2.10 on 2024-02-12 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_therapist_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpatient',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.kfupmdepartment'),
        ),
    ]
