# Generated by Django 4.2.10 on 2024-02-23 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_studentpatient_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, unique=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('description_en', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TherapistSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='therapists', to='core.mentalhealthspecialization')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='core.therapist')),
            ],
        ),
    ]
