# Generated by Django 4.2.10 on 2024-03-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mentalhealthspecialization_therapistspecialization'),
        ('chat', '0003_alter_chatbot_user_profile_chatroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoomFeedeback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'the chat room feedback is pending'), ('REVIEWED', 'the chat room feedback has been reviewed')], default='PENDING', max_length=255)),
                ('feedback', models.TextField()),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='chat.chatroom')),
                ('ending_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ending_room_feedbacks', to='chat.chatmessage')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='core.studentpatient')),
                ('starting_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='starting_room_feedbacks', to='chat.chatmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatRoomFeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='chat.chatroomfeedeback')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_responses', to='core.therapist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
