# Generated by Django 4.2.10 on 2024-03-11 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroomfeedeback_chatroomfeedbackresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='response_len',
            new_name='max_response_tokens',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0.7, max_digits=3, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='top_p',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
