# Generated by Django 4.2.10 on 2024-03-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_response_len_chatbot_max_response_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
