# Generated by Django 4.2.10 on 2024-03-13 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatmessage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='top_p',
            field=models.DecimalField(decimal_places=2, default=0.7, max_digits=3, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
