# Generated by Django 4.2.10 on 2024-03-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chatmessage_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroomfeedeback',
            old_name='starting_message',
            new_name='target_message',
        ),
        migrations.RemoveField(
            model_name='chatroomfeedeback',
            name='ending_message',
        ),
    ]
