# Generated by Django 4.2.10 on 2024-03-13 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_rename_starting_message_chatroomfeedeback_target_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomfeedeback',
            name='target_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_feedbacks', to='chat.chatmessage'),
        ),
    ]
