# Generated by Django 4.2.10 on 2024-03-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_chatmessage_chat_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroomfeedeback',
            name='chat_room',
        ),
    ]
