# Generated by Django 4.2.10 on 2024-03-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_chatroomfeedeback_chat_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
