# Generated by Django 5.0.1 on 2024-01-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashed_email',
            field=models.TextField(default='meow'),
            preserve_default=False,
        ),
    ]
