# Generated by Django 4.2.9 on 2024-02-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(error_messages={'unique': 'A user with that username already exists.'}, unique=True),
        ),
    ]
