# Generated by Django 5.0.4 on 2024-04-16 16:50

import core.db.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_studentpatient_overall_sentiment_score'),
        ('sentiment_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesentiment',
            name='anger',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='messagesentiment',
            name='fear',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='messagesentiment',
            name='joy',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='messagesentiment',
            name='sad',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='messagesentiment',
            name='surprise',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reportsentimentmessage',
            name='sentiment_score',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sentimentreport',
            name='sentiment_score',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='StudentPatientSentimentPosture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', core.db.fields.ZeroToOneDecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sentiment_postures', to='core.studentpatient')),
            ],
        ),
    ]
