# Generated by Django 5.0.4 on 2024-04-17 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_studentpatient_overall_sentiment_score'),
        ('sentiment_ai', '0002_alter_messagesentiment_anger_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentpatientsentimentposture',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='sentimentreport',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 19, 9, 6, 144562, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentimentreport',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 19, 9, 14, 888246, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentimentreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='studentpatientsentimentposture',
            unique_together={('patient', 'date')},
        ),
    ]
