# Generated by Django 5.0.4 on 2024-04-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_ai', '0003_alter_studentpatientsentimentposture_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentimentreport',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='sentimentreport',
            name='start_at',
        ),
    ]
