# Generated by Django 5.0.4 on 2024-04-17 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_ai', '0004_remove_sentimentreport_end_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentimentreport',
            name='sentiment_analysis',
        ),
        migrations.AlterField(
            model_name='reportsentimentmessage',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_report', to='sentiment_ai.messagesentiment'),
        ),
    ]
