# Generated by Django 5.0.4 on 2024-04-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_ai', '0005_remove_sentimentreport_sentiment_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsentimentmessage',
            name='sentiment_score',
        ),
    ]
