# Generated by Django 5.0.4 on 2024-04-26 15:26

import core.db.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_ai', '0007_sentimentreport_report_ending_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesentiment',
            name='adhd',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagesentiment',
            name='anxiety',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagesentiment',
            name='autism',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagesentiment',
            name='bipolar',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagesentiment',
            name='depression',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagesentiment',
            name='no_mental_disorder',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagesentiment',
            name='ocd',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentimentreport',
            name='adhd_score',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentimentreport',
            name='anxiety_score',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentimentreport',
            name='autism_score',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentimentreport',
            name='bipolar_score',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentimentreport',
            name='depression_score',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentimentreport',
            name='no_mental_disorder_score',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentimentreport',
            name='ocd_score',
            field=core.db.fields.ZeroToOneDecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
    ]
