# Generated by Django 4.2.10 on 2024-03-17 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_mentalhealthspecialization_therapistspecialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='surveys/')),
                ('active', models.BooleanField(default=False)),
                ('ready_to_publish', models.BooleanField(default=False)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.therapist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TherapistSurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.TextField(null=True)),
                ('question_type', models.CharField(default='text', max_length=255)),
                ('answer', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('ready_to_publish', models.BooleanField(default=False)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.therapistsurvey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TherapistSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_response_patients', to='core.studentpatient')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.therapistsurvey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TherapistSurveyQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('answer', models.JSONField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_response_answers', to='surveys.therapistsurveyquestion')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_response_answers', to='surveys.therapistsurvey')),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_answers', to='surveys.therapistsurveyresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
