# Generated by Django 4.2.10 on 2024-03-19 08:19

from django.db import migrations, models
import surveys.enums


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_rename_question_therapistsurveyquestion_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapistsurveyquestion',
            old_name='answer',
            new_name='schema',
        ),
        migrations.AlterField(
            model_name='therapistsurveyquestion',
            name='question_type',
            field=models.CharField(choices=[(surveys.enums.SurveyQuestionTypes['TEXT'], 'A question of type raw text'), (surveys.enums.SurveyQuestionTypes['MULTIPLE_CHOICE'], 'A question of type: multiple choice')], default='text', max_length=255),
        ),
    ]
