# Generated by Django 4.2.10 on 2024-03-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_rename_answer_therapistsurveyquestion_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistsurveyresponse',
            name='status',
            field=models.CharField(choices=[('PENDING', 'The survey has not been completed yet'), ('COMPLETED', 'The survey has been completed')], default='PENDING', max_length=255),
        ),
    ]
