# Generated by Django 4.2.10 on 2024-03-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mentalhealthspecialization_therapistspecialization'),
        ('surveys', '0004_therapistsurveyresponse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistsurveyquestion',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='therapistsurvey',
            unique_together={('therapist', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='therapistsurveyquestion',
            unique_together={('survey', 'description')},
        ),
    ]
