# Generated by Django 4.2.10 on 2024-03-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_alter_therapistsurveyquestion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='therapistsurveyquestion',
            unique_together={('survey', 'description'), ('survey', 'index')},
        ),
    ]
