# Generated by Django 4.2.10 on 2024-03-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_alter_therapistsurveyquestion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistsurveyquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'A question of type raw text'), ('multiple_choice', 'A question of type: multiple choice')], default='text', max_length=255),
        ),
    ]
