# Generated by Django 4.2.10 on 2024-03-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_alter_therapistsurveyquestion_question_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='therapistsurvey',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='therapistsurvey',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
