# Generated by Django 4.2.10 on 2024-03-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_alter_therapistsurvey_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistsurvey',
            name='ready_to_publish',
        ),
        migrations.RemoveField(
            model_name='therapistsurveyquestion',
            name='ready_to_publish',
        ),
        migrations.AlterField(
            model_name='therapistsurveyquestion',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
