# Generated by Django 4.2.10 on 2024-03-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_remove_therapistsurvey_ready_to_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistsurveyquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='survey-questions/'),
        ),
    ]
