# Generated by Django 4.2.10 on 2024-03-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_therapistsurveyquestion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistsurvey',
            name='name',
            field=models.CharField(default='dumm', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapistsurveyquestion',
            name='description',
            field=models.TextField(default='dumm'),
            preserve_default=False,
        ),
    ]
