# Generated by Django 4.2.10 on 2024-03-25 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mentalhealthspecialization_therapistspecialization'),
        ('surveys', '0013_alter_therapistsurvey_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistsurvey',
            name='therapist',
        ),
        migrations.AddField(
            model_name='therapistsurvey',
            name='created_by',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.PROTECT, related_name='created_surveys', to='core.therapist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapistsurvey',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_surveys', to='core.therapist'),
        ),
    ]
