# Generated by Django 4.2.10 on 2024-03-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_remove_therapistsurvey_therapist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistsurveyquestion',
            name='index',
            field=models.PositiveIntegerField(),
        ),
    ]
