# Generated by Django 4.2.10 on 2024-03-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_alter_therapistsurveyquestion_index'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='therapistsurveyquestionresponse',
            unique_together={('survey_response', 'question')},
        ),
    ]
