# Generated by Django 4.2.10 on 2024-03-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_alter_therapistsurveyquestion_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistsurvey',
            name='description',
            field=models.TextField(default='the intereseting description'),
            preserve_default=False,
        ),
    ]
