# Generated by Django 4.2.10 on 2024-04-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_therapistsurvey_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistsurveyresponse',
            name='status',
            field=models.CharField(choices=[('PENDING', 'The survey has not been completed yet'), ('CANCELLED', 'The response has been cancelled due to a cancelled appointment'), ('COMPLETED', 'The survey has been completed')], default='PENDING', max_length=255),
        ),
    ]
