# Generated by Django 4.2.9 on 2024-02-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_end_at_appointment_start_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistassignment',
            name='therapist',
        ),
        migrations.AddField(
            model_name='therapistassignment',
            name='therapist_timeslot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_assignments', to='appointments.availabilitytimeslot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapistassignment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], max_length=20),
        ),
    ]
