# Generated by Django 4.2.9 on 2024-02-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_availabilitytimeslotgroup_availabilitytimeslot_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreferralrequest',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='referral_request', to='appointments.appointment'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AppointmentReferral',
        ),
    ]
