# Generated by Django 4.2.9 on 2024-02-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_patientreferralrequest_appointment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentFeedback',
        ),
    ]
