# Generated by Django 4.2.9 on 2024-02-09 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_patientreferralrequest_responding_therapist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreferralrequest',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_request', to='appointments.appointment'),
        ),
    ]
