# Generated by Django 4.2.9 on 2024-02-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_alter_patientreferralrequest_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
