# Generated by Django 4.2.9 on 2024-02-09 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_alter_appointment_end_at_alter_appointment_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_appointments', to='appointments.availabilitytimeslot'),
        ),
    ]
