# Generated by Django 4.2.10 on 2024-02-12 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_alter_appointment_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitytimeslot',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appointments.availabilitytimeslotgroup'),
        ),
    ]
