# Generated by Django 4.2.10 on 2024-02-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_alter_availabilitytimeslot_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistassignment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20),
        ),
    ]
