# Generated by Django 4.2.10 on 2024-02-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_appointment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='active',
        ),
        migrations.AddField(
            model_name='availabilitytimeslot',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
