# Generated by Django 4.2.10 on 2024-03-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_alter_therapistsurveyquestion_schema'),
        ('appointments', '0017_remove_appointment_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitytimeslot',
            name='entry_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='availability_timeslots', to='surveys.therapistsurvey'),
        ),
    ]
