# Generated by Django 4.2.10 on 2024-04-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_alter_therapistsurveyresponse_status'),
        ('appointments', '0018_availabilitytimeslot_entry_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING_THERAPIST', 'Pending Therapist'), ('PENDING_SURVEY_RESPONE', 'Pending Survey Response'), ('PENDING_PATIENT', 'Pending Patient'), ('CONFIRMED', 'Confirmed'), ('CANCELLED_BY_PATIENT', 'Cancelled By Patient'), ('CANCELLED_BY_THERAPIST', 'Cancelled By Therapist'), ('COMPLETED', 'Completed')], max_length=40),
        ),
        migrations.CreateModel(
            name='AppointmentSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='survey_response', to='appointments.appointment')),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_responses', to='surveys.therapistsurveyresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
