# Generated by Django 4.2.10 on 2024-04-05 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_alter_therapistsurveyresponse_status'),
        ('appointments', '0019_alter_appointment_status_appointmentsurveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsurveyresponse',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_responses', to='surveys.therapistsurvey'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING_THERAPIST', 'Pending Therapist'), ('PENDING_SURVEY_RESPONSE', 'Pending Survey Response'), ('PENDING_PATIENT', 'Pending Patient'), ('CONFIRMED', 'Confirmed'), ('CANCELLED_BY_PATIENT', 'Cancelled By Patient'), ('CANCELLED_BY_THERAPIST', 'Cancelled By Therapist'), ('COMPLETED', 'Completed')], max_length=40),
        ),
    ]
