# Generated by Django 4.2.10 on 2024-04-05 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_alter_therapistsurveyresponse_status'),
        ('appointments', '0020_appointmentsurveyresponse_survey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsurveyresponse',
            name='survey_response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='linked_appointment', to='surveys.therapistsurveyresponse'),
        ),
    ]
