name: Backen_test
on: [pull_request, push]

jobs:
  test_project:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_S3_REGION_NAME: ${{ secrets.AWS_S3_REGION_NAME }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DEBUG: ${{ secrets.DEBUG }}
      EMBEDDING_COLLECTION_NAME: ${{ secrets.EMBEDDING_COLLECTION_NAME }}
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SIMPLE_JWT_SIGNING_KEY: ${{ secrets.SIMPLE_JWT_SIGNING_KEY }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run the test
        run: |
          python -W ignore manage.py test